site_name: RayforceDB
repo_url: https://github.com/singaraiona/rayforce
repo_name: GitHub

theme:
  name: material
  # custom_dir: overrides
  icon:
    repo: fontawesome/brands/github 
  # logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - header.autohide
    - announce.dismiss
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.copy
    # - content.action.view
    - toc.follow

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/lumx


extra:
    social:
      - icon: fontawesome/brands/github 
        link: https://github.com/singaraiona
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/anton-kundenko-a22a3667
      - icon: fontawesome/solid/paper-plane
        link: mailto:<singaraiona@gmail.com>

copyright: Copyright &copy; 2023 RayforceDB

plugins:
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - admonition
  - footnotes

extra_css:
  - css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/asciinema-player/2.6.1/asciinema-player.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/asciinema-player/2.6.1/asciinema-player.js
  
# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Getting Started: 
      - Install: content/getstarted/install.md
      - Tutorial: content/getstarted/tutorial.md
    - Reference card: content/reference.md
    - Syntax: content/syntax.md
    - Atomic functions: content/atomic.md
    - Math:
      - Add: content/math/add.md
      - Sub: content/math/sub.md
      - Mul: content/math/mul.md
      - Div: content/math/div.md
      - Fdiv: content/math/fdiv.md
      - Mod: content/math/mod.md
      - Sum: content/math/sum.md
      - Avg: content/math/avg.md
      - Min: content/math/min.md
      - Max: content/math/max.md
    - Evaluation Control:
      - If: content/control/if.md
      - Try: content/control/try.md
      - Exit: content/control/exit.md
    - Compose:
      - Casting: content/compose/as.md
      - Concat: content/compose/concat.md
      - Create Dict: content/compose/dict.md
      - Create Table: content/compose/table.md
      - Create List: content/compose/list.md
      - Create Vector: content/compose/enlist.md
      - Group: content/compose/group.md
      - GUID: content/compose/guid.md
      - Rand: content/compose/rand.md
      - Reverse: content/compose/reverse.md
      - Til: content/compose/til.md
    - Env:
      - Set: content/env/set.md
      - Let: content/env/let.md
      - Get env: content/env/env.md
      - Memstat: content/env/memstat.md
    - IO:
      - Read CSV: content/io/csv.md
      - Print: content/io/print.md
      - Println: content/io/println.md
      - Read: content/io/read.md
      - Write: content/io/write.md
    - Logic:
      - And: content/logic/and.md
      - Or: content/logic/or.md
      - Like: content/logic/like.md
    - REPL:
      - Parse: content/repl/parse.md
      - Eval: content/repl/eval.md
      - Load: content/repl/load.md
    - Queries: content/queries.md
    - Serialization: content/serialization.md
    - Interfacing: 
      - IPC: content/interfacing/ipc.md
      - Extending: content/interfacing/extending.md
  - FAQ: content/faq.md
  - License: content/license.md
