name = "RayforceDB"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Fast columnar time-series database."

tags = ["database", "columnar", "big data", "trading", "time-series"]
features = [
  "security aware",
  "fast by default",
  "seo-ready",
  "development tools",
  "bootstrap framework",
  "netlify-ready",
  "full text search",
  "page layouts",
  "dark mode",
]

[author]
name = "Anton Kundenko"
homepage = "https://github.com/singaraiona/rayforce/"
